"""
Terminal log dashboard using Rich.
Renders stats safely with graceful fallbacks for missing data.
"""

from datetime import datetime
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text

console = Console()

_IP_BAR = 20
_CHART_W = 40


def _bar(count: int, peak: int, width: int) -> str:
    # Builds proportional ASCII bar for simple visualization.
    # Safely handles divide-by-zero cases.
    if peak == 0:
        return ""
    return "#" * round(count / peak * width)


def print_report(stats: dict) -> None:
    """
    Renders full log report from precomputed stats dict.
    Each section safely handles missing or empty data.
    """

    # Parse quality metrics
    total = stats.get("total_lines", 0)
    parsed = stats.get("parsed", 0)
    skipped = stats.get("skipped", 0)

    parsed_pct = round(parsed / total * 100, 1) if total else 0.0
    skipped_pct = round(skipped / total * 100, 1) if total else 0.0

    pct_color = "green" if parsed_pct >= 95 else "yellow" if parsed_pct >= 80 else "red"

    row = Text()
    row.append(f"Total Lines: {total}    ")
    row.append(f"Parsed: {parsed} ({parsed_pct}%)", style=pct_color)
    row.append(f"    Skipped: {skipped} ({skipped_pct}%)")

    console.print(Panel(row, title="Parse Quality", border_style="bright_blue"))

    # Slow endpoints table
    slow = stats.get("slow_endpoints") or []

    t1 = Table(title="Top Slow Endpoints", border_style="bright_blue")
    t1.add_column("PATH", style="cyan", no_wrap=True)
    t1.add_column("AVG ms", style="yellow", justify="right")
    t1.add_column("MAX ms", style="red", justify="right")
    t1.add_column("REQS", style="white", justify="right")

    if slow:
        for i, (path, avg, peak, count) in enumerate(slow):
            t1.add_row(path, f"{avg:.1f}", f"{peak:.1f}", str(count), style="bold" if i == 0 else "")
    else:
        t1.add_row("[dim]No data available[/dim]", "", "", "")

    console.print(t1)

    # Error breakdown
    error_codes = stats.get("error_codes") or {}
    missing_status = stats.get("missing_status", 0)

    t2 = Table(title="Error Summary", border_style="bright_blue")
    t2.add_column("STATUS", style="bold red", justify="right")
    t2.add_column("COUNT", justify="right")
    t2.add_column("% OF ERRORS", justify="right")

    if error_codes:
        total_errors = sum(error_codes.values())
        for code, cnt in sorted(error_codes.items()):
            pct = round(cnt / total_errors * 100, 1) if total_errors else 0.0
            t2.add_row(str(code), str(cnt), f"{pct}%")
    else:
        t2.add_row("[dim]No errors found[/dim]", "", "")

    console.print(t2)

    if missing_status > 0:
        console.print(f"  Missing status codes: {missing_status}", style="dim italic")

    # Top IP traffic
    top_ips = stats.get("top_ips") or []

    t3 = Table(title="Top IPs by Traffic", border_style="bright_blue")
    t3.add_column("IP ADDRESS")
    t3.add_column("REQUESTS", justify="right")
    t3.add_column("TRAFFIC")

    if top_ips:
        peak_ip = max(c for _, c in top_ips)
        for ip, cnt in top_ips:
            t3.add_row(ip, str(cnt), _bar(cnt, peak_ip, _IP_BAR))
    else:
        t3.add_row("[dim]No data available[/dim]", "", "")

    console.print(t3)

    # Traffic timeline view
    console.rule("[bold bright_blue] Traffic Timeline [/bold bright_blue]")

    timeline = stats.get("timeline") or {}

    if timeline:
        all_items = list(timeline.items())
        hidden = len(all_items) - 20
        items = all_items[-20:]
        peak_t = max(c for _, c in items)

        if hidden > 0:
            console.print(f"  [dim]... {hidden} earlier buckets not shown[/dim]")

        for ts, cnt in items:
            ratio = cnt / peak_t if peak_t else 0
            style = "dim" if ratio < 0.2 else "bold bright_white" if ratio > 0.8 else "white"

            bar = _bar(cnt, peak_t, _CHART_W)
            console.print(f"  {ts}  {bar:<{_CHART_W}}  {cnt} requests", style=style)
    else:
        console.print("  [dim]No timeline data available[/dim]")

    # Footer info
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    footer = f"Generated by log-analyzer | {now} | {stats.get('parsed', 0)} events"
    console.print(f"\n[dim]{footer}[/dim]")